version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ManagerScrumX
      MYSQL_USER: rayan
      MYSQL_PASSWORD: 123
    networks:
      - my-network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
